### ISSUE TITLE
[BUG] Doesn't compile on M1

### ISSUE THREAD

**Issue by ghost** [nativeos/homebrew-i386-elf-toolchain#10]
```
Last 15 lines from /Users/user/Library/Logs/Homebrew/i386-elf-gcc/02.make:
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [lto1] Error 1
make[1]: *** Waiting for unfinished jobs....
Undefined symbols for architecture arm64:
  "_host_hooks", referenced from:
      c_common_no_more_pch() in c-pch.o
      toplev::main(int, char**) in libbackend.a(toplev.o)
      gt_pch_save(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_restore(__sFILE*) in libbackend.a(ggc-common.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cc1plus] Error 1
rm gcc.pod
make: *** [all-gcc] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by danirod** [comment]
Pinning this issue to receive feedback from anyone since I don't own an ARM64 Mac yet.

I've updated the formulas to the latest version of Binutils (2.36.1, https://github.com/nativeos/homebrew-i386-elf-toolchain/pull/11) and GCC (11.1.0, https://github.com/nativeos/homebrew-i386-elf-toolchain/pull/12). If it is still not compiling, I'd assume that support for the M1 hasn't arrived upstream yet; would propose installing the application using Rosetta 2 in that case.

**Comment by hinoshiba** [comment]
thank you for your update.
I tried install on Rosetta2 And It's work.

### install commnads
```
xcode-select --install
softwareupdate --install-rosetta --agree-to-license
arch -arch x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
arch -arch x86_64 /usr/local/bin/brew tap nativeos/i386-elf-toolchain
arch -arch x86_64 /usr/local/bin/brew install i386-elf-binutils i386-elf-gcc
```

### version
```
hinoshiba@MBPM1Pro ~% i386-elf-gcc -v
Using built-in specs.
COLLECT_GCC=i386-elf-gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/i386-elf-gcc/11.1.0_2/libexec/gcc/i386-elf/11.1.0/lto-wrapper
Target: i386-elf
Configured with: ../configure --prefix=/usr/local/Cellar/i386-elf-gcc/11.1.0_2 --target=i386-elf --disable-multilib --disable-nls --disable-werror --without-headers --without-isl --enable-languages=c,c++
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 11.1.0 (GCC)
hinoshiba@MBPM1Pro ~%
```

**Comment by danirod** [comment]
Thanks for the report! This is good to know. If GCC 11 works under Rosetta, this is good enough already (I read in tech news that native support for M1 is coming in GCC 12). I suppose that GCC 9 was too old for Rosetta anyway. I need to update more often this tap..

Closing this issue to mark it as fixed. Thank you very much!

**Comment by Kyle-Ye** [comment]
I also encountered this bug. And according to the upstream https://github.com/riscv-software-src/homebrew-riscv/issues/47, we could fix it by commenting the 2 lines of gcc's config file **without using Rosetta mode**.

Maybe this will be fixed by the next version of gcc, but currently I just modify it and compress it to the repo for my personal use due to the limitation of homebrew(Which will check the checksum of the zip file). 

https://github.com/Kyle-Ye/homebrew-i386-elf-toolchain
