### ISSUE TITLE
i386-elf-gcc fails to build on debian stretch

### ISSUE THREAD

**Issue by Guerra24** [nativeos/homebrew-i386-elf-toolchain#2]
![image](https://puu.sh/vkEDi/1a9f237308.png)
[Log File](https://github.com/nativeos/homebrew-i386-elf-toolchain/files/923267/02.make.txt)

**Comment by danirod** [comment]
This issue will be kept on stand by as well until provided packages are upgraded in order to assert whether it has to do with compiling an older version of GCC with a newer version of GCC.

**Comment by danirod** [comment]
Can confirm it fails to build on Linux using the script from nativeos/i386-elf-toolchain as well. I'm assuming it has to do with using a newer GCC (GCC 6) to build an older GCC (GCC 5), which is often not a good idea.

A workaround is compiling via clang or via gcc-5 if the latter is available on the host package manager. It will be required to add `CC=clang CXX=clang++` or `CC=gcc-5 CXX=g++-5` to the `./configure` command.

GCC 5 generates no warnings during compilation. However, because this tap has a preference for MacOS X, I'll assume the system already has clang and clang++ in order to reduce the amount of dependencies for the recipes. clang and clang++ are part of the XCode Command Line Tools and on MacOS X invoking gcc and g++ actually invokes clang.

I'm creating a control task (#3) to keep track of this because I'd rather not change versions now until I finish the build scripts. Once updated versions, maybe we can talk about side-supporting Linuxbrew.
