### ISSUE TITLE
Reports that Command Line Tools are too outdated

### ISSUE THREAD

**Issue by KartikAiyer** [nativeos/homebrew-i386-elf-toolchain#22]
Hello , I'm running Mac OS Monterey 12.2.1 with Xcode 13.2.1 installed.  
I added the tap and when I try to install binutils I get the following

```
> brew install nativeos/i386-elf-toolchain/i386-elf-binutils                   ~/i386-compiler@Kartiks-MacBook-Air.local

Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://sourceware.org/pub/binutils/releases/binutils-2.37.tar.xz
Already downloaded: /Users/kartikaiyer/Library/Caches/Homebrew/downloads/09934f6bacd23b0cc6993db80c80c0fe399ce47eb78f39600eda4c04d2cf41b4--binutils-2.37.tar.xz
==> Installing i386-elf-binutils from nativeos/i386-elf-toolchain
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.2.1.
```
I have installed the Command Line Tools and running `xcode-select` just says to run softwareupdate
```
> sudo xcode-select --install                                                  ~/i386-compiler@Kartiks-MacBook-Air.local
Password:
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
In XCode it confirmst that I have Command Line Tools for 13.2.1 
<img width="826" alt="Screen Shot 2022-02-12 at 1 39 57 PM" src="https://user-images.githubusercontent.com/2114735/153729332-4388400a-43c2-4cd5-9d7e-ba0637f6cc9d.png">

I'd appreciate any pointers or suggestions about this. 

Thanks

**Comment by danirod** [comment]
I've had this issue happening a few times in the past to me when compiling things from source and the thing that fixed it for me was to completely delete the directory where xcode-select install its things and then reinstall with xcode-select --install again: https://github.com/Homebrew/brew/issues/4101#issuecomment-393046028

Deleting directories sound risky so I'd consider either thinking twice, making backups or just renaming the directory (it is much safer).

This is not an issue with this tap but with macOS in general, as I've seen this happening since Mojave or Catalina. Haven't upgraded to Monterey because my MacBook is too old, but I am pleased to hear this bug is still around :')

**Comment by KartikAiyer** [comment]
Thanks for the quick response. I’ll give it a shot.

**Comment by danirod** [comment]
Preventively closing this then, feel free to reopen if it still happens.
