### ISSUE TITLE
How to include c standard library?

### ISSUE THREAD

**Issue by xiaohk** [nativeos/homebrew-i386-elf-toolchain#6]
Thanks for making this formula. I have successfully installed `i386-elf-gcc` and `i386-elf-binutils`, but when I use `i386-elf-gcc` to compile a test c file, I got the following errors:

```
JayWong Test $ i386-elf-gcc --sysroot=usr/includes test.c
test.c:1:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
```

Do you happen to know how to add c standard library for compiling?

**Comment by danirod** [comment]
If you use the --sysroot flag when calling GCC, it will look for headers on ${sysroot}/usr/include, so GCC may actually be looking for stdio.h on `usr/includes/usr/include/stdio.h`. Check that file exists. Same for libraries.

Aside from that, not much. This compiler builds pure ELF binaries but makes no assumptions about a particular C library since there may not exist one at runtime (i.e. this compiler does not generate Linux executables or FreeBSD executables).

If you are looking into compiling Linux software from Mac, you should compile a Linux cross-compiler using something like crosstool to get i686-pc-linux-gnu-gcc or x86_64-pc-linux-gcc.
If you are looking into compiling pure ELF binaries, you should port newlib, musl, or another C runtime library, but I still don't have experience with this as I haven't advanced that much with my OS yet to have a standard library.
